name: base
channels:
  - defaults
  - rmg
  - conda-forge
dependencies:
  - python=3.7
  - rmg=3.1.0
  - rmgdatabase=3.1.0
  - requests
  - PyGithub
  - python-dotenv
  - habanero
  - pip
  - pip:
    - datamodel-code-generator[http]
